[package]
name = "udptk"
version = "0.1.0"
edition = "2021"
authors = ["Yusong Lai <yusong.lai@icloud.com>"]
license = "MIT OR Apache-2.0"

[[bin]]
name = "udptk"
path = "src/main.rs"

[profile.release]
lto = "thin"
strip = "symbols"
panic = "abort"

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.4", features = ["derive"] }
rand = "0.8.5"
thiserror = "1.0.58"
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
