[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.4"
edition = "2021"
authors = ["Yusong Lai <yusong.lai@icloud.com>"]
repository = "https://github.com/whisperpine/udptk"
readme = "README.md"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "1"
tracing = "0.1"
anyhow = "1"

[profile.release]
lto = "thin"
strip = "symbols"
panic = "abort"
