# Use this file for local test.

services:
  listen:
    build:
      context: .
      target: final
      dockerfile: Dockerfile.dev
    environment:
      RUST_LOG: udptk=debug
    ports:
      - 6777:6777/udp
    command: listen -p 6777

  send:
    build:
      context: .
      target: final
      dockerfile: Dockerfile.dev
    environment:
      RUST_LOG: udptk=debug
    command: send -t listen:6777 yahaha
    depends_on:
      - listen
